### ISSUE TITLE
create and add illustrative pictures

### ISSUE THREAD

**Issue by whilei** [ETCDEVTeam/sidekick-doc#1]

**Comment by darcyreno** [comment]
I added that diagram to github

**Comment by darcyreno** [comment]
Adding Stevan to get a sense of what we've put in place so far for documentation on this project,

**Comment by darcyreno** [comment]
OK, this is live on Medium
@Igor Artamonov Feel free to post to Twitter

**Comment by whilei** [comment]
👍 
closing issue since bespoke diagrams have been added
